### ISSUE TITLE
Is it possible to detect User Gender/Age/Location?

### ISSUE THREAD

**Issue by pitanello** [zwetan/as3-universal-analytics#33]
I know Google Analytics allow you to know more about your users but i didn't find anything related in the API of this library, should i use Firebase instead?
Thanks!

**Comment by zwetan** [comment]
Because it is not done with the API, those demographics are detected on the backend.

documentation for Google Analytics
[About Demographics and Interests](https://support.google.com/analytics/answer/2799357?hl=en)

documentation for Firebase
[Automatically collected user properties](https://support.google.com/firebase/answer/6317486?hl=en)

see [How Google determines demographic information](https://support.google.com/adwords/answer/2580383?hl=en) from AdsWord

> When people are signed in from their Google Account, we may use location signals and demographics derived from their settings. Consumers can edit their demographic information by visiting Ads Settings. In addition, some sites might provide us with demographic information that people share on certain websites, such as social networking sites.
> 
> For people who aren't signed in to their Google Account, we sometimes infer their demographic information based on their activity from Google properties or the Display Network. For example, when people browse YouTube or sites on the Display Network, Google may store an identifier in their web browser, using a “cookie.” That browser may be associated with certain demographic categories, based on sites that were visited.

All those services: Google Analytics, AdWords, AdSense, Google Display Network, Firebase, etc. use the same logic.
